<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <artifactId>gsrs-module-invitro-pharmacology</artifactId>
        <groupId>gov.nih.ncats</groupId>
        <version>3.2.5-SNAPSHOT </version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>gsrs-module-invitro-pharmacology-spring-boot-starter</artifactId>
    <name>gsrs-module-invitro-pharmacology-spring-boot-starter</name>

    <dependencies>
        <!-- INVITRO PHARMACOLOGY MODULE Autoconfigure Dependencies -->
        <dependency>
            <groupId>gov.nih.ncats</groupId>
            <artifactId>gsrs-module-invitro-pharmacology-spring-boot-autoconfigure</artifactId>
            <version>${gsrs.invitro-pharmacology.version}</version>
        </dependency>

        <!-- SPRING BOOT Dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

    </dependencies>

</project>
